export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'
export const TASK_CHANGED = 'TASK_CHANGED'