export const ADD_PROJECT = 'ADD_PROJECT'
export const OPEN_PROJECT = 'OPEN_PROJECT'
export const CLOSE_PROJECT = 'CLOSE_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'

export const SET_PROJECTS = 'SET_PROJECTS'
export const SET_CURRENT_PROJECT_KEY = 'SET_CURRENT_PROJECT_KEY'

export const SET_TASKS = 'SET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const CHANGE_TASK = 'CHANGE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'